"""empty message

Revision ID: 1101cf8cbe05
Revises: 7235608b54ea
Create Date: 2017-01-20 00:40:46.322492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1101cf8cbe05'
down_revision = '7235608b54ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('likes', 'bucketitem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'bucketitems', ['bucketitem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.alter_column('likes', 'bucketitem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
