"""empty message

Revision ID: 38d42321bf23
Revises: ba6b1eb2d178
Create Date: 2017-01-11 13:26:37.352707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d42321bf23'
down_revision = 'ba6b1eb2d178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketitems', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketitems', 'timestamp')
    # ### end Alembic commands ###
