"""empty message

Revision ID: 7072116142b3
Revises: f8692ca33d7a
Create Date: 2016-12-20 05:58:43.200525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7072116142b3'
down_revision = 'f8692ca33d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
