"""empty message

Revision ID: 753ea633e672
Revises: 38d42321bf23
Create Date: 2017-01-12 22:41:56.313307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753ea633e672'
down_revision = '38d42321bf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketitems', sa.Column('description', sa.String(), nullable=False))
    op.add_column('bucketitems', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.add_column('bucketitems', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('bucketitems', sa.Column('photo_path', sa.String(), nullable=True))
    op.drop_column('bucketitems', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketitems', sa.Column('post', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('bucketitems', 'photo_path')
    op.drop_column('bucketitems', 'is_private')
    op.drop_column('bucketitems', 'is_done')
    op.drop_column('bucketitems', 'description')
    # ### end Alembic commands ###
